"""meeting dokument optional machen

Revision ID: 43ad9f389ced
Revises: c7e2a1f4d9b3
Create Date: 2026-08-14 15:07:54.424225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ad9f389ced'
down_revision: Union[str, Sequence[str], None] = 'c7e2a1f4d9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.alter_column('document_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.alter_column('document_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
