"""korrektur dokument hash unique zu index

Revision ID: 931b876860b6
Revises: a4bdfa5978ab
Create Date: 2026-08-14 11:03:00.521237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931b876860b6'
down_revision: Union[str, Sequence[str], None] = 'a4bdfa5978ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_document_project_hash'), type_='unique')
        batch_op.create_index('ix_document_project_hash', ['project_id', 'datei_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('ix_document_project_hash')
        batch_op.create_unique_constraint(batch_op.f('uq_document_project_hash'), ['project_id', 'datei_hash'])

    # ### end Alembic commands ###
