"""initial schema

Revision ID: a4bdfa5978ab
Revises: 
Create Date: 2026-08-14 09:37:52.736223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4bdfa5978ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claude_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('claude_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_model_name', sa.String(length=200), nullable=False),
    sa.Column('candidate_k_vector', sa.Integer(), nullable=False),
    sa.Column('candidate_k_keyword', sa.Integer(), nullable=False),
    sa.Column('final_k', sa.Integer(), nullable=False),
    sa.Column('chunk_ziel_tokens', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap_tokens', sa.Integer(), nullable=False),
    sa.Column('fusion_verfahren', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('zweck', sa.Enum('CHAT', 'IMAGE_ANALYSIS', 'DOCUMENT_SUMMARY', name='apiusagepurpose', native_enum=False, length=30), nullable=False),
    sa.Column('modell', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('dauer_ms', sa.Integer(), nullable=False),
    sa.Column('erfolg', sa.Boolean(), nullable=False),
    sa.Column('fehlertyp', sa.String(length=200), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_usage_logs_project_id'), ['project_id'], unique=False)

    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=300), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('zuletzt_aktualisiert_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_conversations_project_id'), ['project_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.Enum('MEETING', 'SYSTEMEINSTELLUNG', 'PROZESS', 'NOTIZ', 'DATEI', 'BILD', 'SONSTIGES', name='documenttype', native_enum=False, length=30), nullable=False),
    sa.Column('titel', sa.String(length=300), nullable=False),
    sa.Column('inhalt', sa.Text(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ki_analyse_rohtext', sa.Text(), nullable=True),
    sa.Column('original_dateipfad', sa.String(length=500), nullable=True),
    sa.Column('datei_hash', sa.String(length=64), nullable=True),
    sa.Column('dateiname', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'REVIEW_REQUIRED', 'INDEXING', 'READY', 'FAILED', name='documentstatus', native_enum=False, length=30), nullable=False),
    sa.Column('fehlermeldung', sa.Text(), nullable=True),
    sa.Column('dokumentdatum', sa.Date(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('aktualisiert_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'datei_hash', name='uq_document_project_hash')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_datei_hash'), ['datei_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)

    op.create_table('index_metadata',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('active_index_version', sa.Integer(), nullable=False),
    sa.Column('active_collection_name', sa.String(length=200), nullable=True),
    sa.Column('active_embedding_model_name', sa.String(length=200), nullable=True),
    sa.Column('active_embedding_model_revision', sa.String(length=100), nullable=True),
    sa.Column('active_chunking_strategie_version', sa.String(length=50), nullable=True),
    sa.Column('active_chunk_ziel_tokens', sa.Integer(), nullable=True),
    sa.Column('active_chunk_overlap_tokens', sa.Integer(), nullable=True),
    sa.Column('active_index_erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('rebuild_status', sa.Enum('IDLE', 'REBUILDING', 'FAILED', name='rebuildstatus', native_enum=False, length=20), nullable=False),
    sa.Column('pending_index_version', sa.Integer(), nullable=True),
    sa.Column('pending_collection_name', sa.String(length=200), nullable=True),
    sa.Column('rebuild_started_at', sa.DateTime(), nullable=True),
    sa.Column('rebuild_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rolle', sa.String(length=200), nullable=True),
    sa.Column('kontaktinfo', sa.String(length=300), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_project_id'), ['project_id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_tag_project_name')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_project_id'), ['project_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('rolle', sa.Enum('USER', 'ASSISTANT', name='chatrole', native_enum=False, length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('quellen', sa.JSON(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('index_version', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('seite', sa.Integer(), nullable=True),
    sa.Column('abschnitt', sa.String(length=300), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('dateiname', sa.String(length=300), nullable=True),
    sa.Column('dokumenttyp', sa.String(length=30), nullable=True),
    sa.Column('dokumentdatum', sa.Date(), nullable=True),
    sa.Column('meeting_datum', sa.Date(), nullable=True),
    sa.Column('meeting_teilnehmer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'index_version', 'chunk_index', name='uq_chunk_document_version_index')
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_index_version'), ['index_version'], unique=False)

    op.create_table('document_tags',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'tag_id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('zusammenfassung', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_document_id'), ['document_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_meetings_project_id'), ['project_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=300), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OFFEN', 'IN_ARBEIT', 'ERLEDIGT', name='taskstatus', native_enum=False, length=20), nullable=False),
    sa.Column('zugewiesen_an', sa.Integer(), nullable=True),
    sa.Column('faellig_am', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zugewiesen_an'], ['people.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_zugewiesen_an'), ['zugewiesen_an'], unique=False)

    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', 'person_id')
    )
    op.create_table('task_documents',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_documents')
    op.drop_table('meeting_participants')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_zugewiesen_an'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_project_id'))
        batch_op.drop_index(batch_op.f('ix_meetings_document_id'))

    op.drop_table('meetings')
    op.drop_table('document_tags')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_index_version'))
        batch_op.drop_index(batch_op.f('ix_chunks_document_id'))

    op.drop_table('chunks')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_conversation_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_project_id'))

    op.drop_table('tags')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_project_id'))

    op.drop_table('people')
    op.drop_table('index_metadata')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_project_id'))
        batch_op.drop_index(batch_op.f('ix_documents_datei_hash'))

    op.drop_table('documents')
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_conversations_project_id'))

    op.drop_table('chat_conversations')
    with op.batch_alter_table('api_usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usage_logs_project_id'))

    op.drop_table('api_usage_logs')
    op.drop_table('projects')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
