"""outlook ordnerueberwachung

Revision ID: afc5c8a63cd4
Revises: b4afc6b41c39
Create Date: 2026-08-18 11:11:52.674532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc5c8a63cd4'
down_revision: Union[str, Sequence[str], None] = 'b4afc6b41c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Briefing-Erweiterung "Outlook-Ordnerueberwachung" (Kernfunktion 12):
    # email_oauth_accounts = globales Microsoft-Konto (id=1-Singleton, wie
    # app_settings), email_watch_configs = Ordner-Zuordnung pro Projekt (1:1,
    # wie index_metadata), outlook_message_id = mail-spezifische
    # Duplikatserkennung am Document.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_oauth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_email', sa.String(length=300), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('access_token_expires_am', sa.DateTime(), nullable=True),
    sa.Column('verbunden_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_watch_configs',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('outlook_ordner_id', sa.String(length=300), nullable=False),
    sa.Column('outlook_ordner_name', sa.String(length=300), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('polling_intervall_minuten', sa.Integer(), nullable=False),
    sa.Column('letzte_abfrage_am', sa.DateTime(), nullable=True),
    sa.Column('letzter_fehler', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outlook_message_id', sa.String(length=300), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_outlook_message_id'), ['outlook_message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_outlook_message_id'))
        batch_op.drop_column('outlook_message_id')

    op.drop_table('email_watch_configs')
    op.drop_table('email_oauth_accounts')
    # ### end Alembic commands ###
