"""model pricing und wechselkurs

Revision ID: b4afc6b41c39
Revises: 43ad9f389ced
Create Date: 2026-08-14 16:52:18.064466

"""
from datetime import date
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4afc6b41c39'
down_revision: Union[str, Sequence[str], None] = '43ad9f389ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modell_name', sa.String(length=100), nullable=False),
    sa.Column('gueltig_ab', sa.Date(), nullable=False),
    sa.Column('input_preis_pro_million_usd', sa.Float(), nullable=False),
    sa.Column('output_preis_pro_million_usd', sa.Float(), nullable=False),
    sa.Column('cache_write_preis_pro_million_usd', sa.Float(), nullable=True),
    sa.Column('cache_read_preis_pro_million_usd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modell_name', 'gueltig_ab', name='uq_model_pricing_modell_gueltig_ab')
    )
    with op.batch_alter_table('model_pricing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_pricing_modell_name'), ['modell_name'], unique=False)

    # server_default noetig: app_settings hat bereits eine bestehende Zeile
    # (Singleton, siehe settings_service) - eine NOT-NULL-Spalte ohne Default
    # liesse sich sonst nicht ergaenzen (SQLite-Batch-Modus kopiert die
    # bestehende Zeile beim Tabellen-Neuaufbau mit).
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('eur_usd_wechselkurs', sa.Float(), nullable=False, server_default='0.92')
        )

    # Startwerte (siehe README "Technische Entscheidungen"): aktuelle
    # Claude-Preise (Stand 14.08.2026, siehe docs.anthropic.com/pricing) fuer
    # die in diesem Projekt tatsaechlich genutzten Modelle. gueltig_ab bewusst
    # auf das Einspielungsdatum dieser Migration - jederzeit in den
    # Einstellungen editierbar bzw. um neue Versionen ergaenzbar (z. B. wenn
    # ein Einfuehrungspreis auslaeuft).
    model_pricing_table = sa.table(
        "model_pricing",
        sa.column("modell_name", sa.String),
        sa.column("gueltig_ab", sa.Date),
        sa.column("input_preis_pro_million_usd", sa.Float),
        sa.column("output_preis_pro_million_usd", sa.Float),
    )
    op.bulk_insert(
        model_pricing_table,
        [
            {
                "modell_name": "claude-opus-5",
                "gueltig_ab": date(2026, 8, 14),
                "input_preis_pro_million_usd": 5.00,
                "output_preis_pro_million_usd": 25.00,
            },
            {
                "modell_name": "claude-sonnet-5",
                "gueltig_ab": date(2026, 8, 14),
                "input_preis_pro_million_usd": 2.00,
                "output_preis_pro_million_usd": 10.00,
            },
            {
                "modell_name": "claude-haiku-4-5-20251001",
                "gueltig_ab": date(2026, 8, 14),
                "input_preis_pro_million_usd": 1.00,
                "output_preis_pro_million_usd": 5.00,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('eur_usd_wechselkurs')

    with op.batch_alter_table('model_pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_pricing_modell_name'))

    op.drop_table('model_pricing')
    # ### end Alembic commands ###
